{
 "title": "Live Host Overview",
 "tags": [ "pcp-live" ],
 "time": { "from": "now-2m", "to": "now+2s" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-live-datasource" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kernel.cpu.util.user" },
    { "expr": "kernel.cpu.util.sys" }
   ]
  },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kernel.all.load" }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "mem.util.cached" },
    { "expr": "mem.physmem" },
    { "expr": "mem.util.free" }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "disk.dev.util" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Per-CPU ms/s busy (User)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kernel.percpu.cpu.user" }
   ]
  },
  {
   "title": "Per-CPU ms/s busy (Sys)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kernel.percpu.cpu.sys" }
   ]
  },
  {
   "title": "User %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kernel.cpu.util.user" }
   ]
  },
  {
   "title": "Sys %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kernel.cpu.util.sys" }
   ]
  },
  {
   "title": "Interrupt %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kernel.cpu.util.intr" }
   ]
  },
  {
   "title": "Wait %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kernel.cpu.util.wait" }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Context switches per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kernel.all.pswitch" }
   ]
  },
  {
   "title": "Runnable",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kernel.all.runnable" }
   ]
  },
  {
   "title": "Run queue latency (us)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "bcc.runq.latency" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "mem.util.used" }
   ]
  },
  {
   "title": "Cached",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "mem.util.cached" }
   ]
  },
  {
   "title": "Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "mem.util.free" }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "mem.vmstat.pgfault" }
   ]
  },
  {
   "title": "Hard fault rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "mem.vmstat.pgmajfault" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network Throughput (in)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "network.interface.in.bytes" }
   ]
  },
  {
   "title": "Network Throughput (out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "network.interface.out.bytes" }
   ]
  },
  {
   "title": "Network Drops (In)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.interface.in.drops" }
   ]
  },
  {
   "title": "Network Drops (Out)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.interface.out.drops" }
   ]
  },
  {
   "title": "Network Packets (In)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.interface.in.packets" }
   ]
  },
  {
   "title": "Network Packets (Out)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.interface.in.packets" }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network.tcpconn.established" },
    { "expr": "network.tcpconn.time_wait" },
    { "expr": "network.tcpconn.close_wait" }
   ]
  },
  {
   "title": "TCP Timeouts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.tcp.timeouts" }
   ]
  },
  {
   "title": "TCP Close-waits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network.tcpconn.close_wait" }
   ]
  },
  {
   "title": "TCP Time Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network.tcpconn.time_wait" }
   ]
  },
  {
   "title": "TCP Established",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network.tcpconn.established" }
   ]
  },
  {
   "title": "TCP Listen Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.tcp.listenoverflows" },
    { "expr": "network.tcp.listendrops" }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "network.tcp.retranssegs" },
    { "expr": "network.tcp.fastretrans" },
    { "expr": "network.tcp.slowstartretrans" },
    { "expr": "network.tcp.synretrans" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "disk.dev.read_rawactive" },
    { "expr": "disk.dev.write_rawactive" }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "disk.dev.read" },
    { "expr": "disk.dev.write" }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "disk.dev.read_bytes" },
    { "expr": "disk.dev.write_bytes" }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "disk.dev.avactive" }
   ]
  },
  {
   "title": "BCC disk latency (us)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "targets": [
    { "expr": "bcc.disk.all.latency" }
   ]
  }
 ]
}