{
 "title": "PCP Vector Container Overview (CGroups v2)",
 "tags": [ "pcp-vector" ],
 "time": { "from": "now-2m", "to": "now+2s" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-vector-datasource" },
   { "name": "container", "query": "containers.name" }
  ]
 },
 "panels": [
  { "title": "$container", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "repeat": "container" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cgroup.cpu.stat.usage",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "utilization"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cgroup.memory.current",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "repeat": "container",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "cgroup.io.stat.rios",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "read $instance"
    },
    {
     "expr": "cgroup.io.stat.wios",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "repeat": "container",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "cgroup.io.stat.rbytes",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "read $instance"
    },
    {
     "expr": "cgroup.io.stat.wbytes",
     "hostspec": "pcp://127.0.0.1?container=$container",
     "legendFormat": "write $instance"
    }
   ]
  }
 ]
}