{
 "title": "PCP Vector Container Overview",
 "tags": [ "pcp-vector" ],
 "time": { "from": "now-2m", "to": "now+2s" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-vector-datasource" },
   { "name": "container", "query": "containers.name" }
  ]
 },
 "panels": [
  { "title": "$container", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "repeat": "container" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "container": "$container", "expr": "cgroup.cpuacct.usage", "legendFormat": "utilization" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "repeat": "container",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "container": "$container", "expr": "cgroup.memory.usage", "legendFormat": "usage" }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "expr": "cgroup.blkio.all.throttle.io_serviced.read",
     "legendFormat": "read"
    },
    {
     "container": "$container",
     "expr": "cgroup.blkio.all.throttle.io_serviced.write",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "container",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "container": "$container",
     "expr": "cgroup.blkio.all.throttle.io_service_bytes.read",
     "legendFormat": "read"
    },
    {
     "container": "$container",
     "expr": "cgroup.blkio.all.throttle.io_service_bytes.write",
     "legendFormat": "write"
    }
   ]
  }
 ]
}