{
 "title": "PCP Redis Host Overview",
 "tags": [ "pcp-redis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-redis-datasource" },
   {
    "name": "host",
    "query": "label_values(kernel.all.uptime, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.load{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.cached{hostname == \"$host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem.physmem{hostname == \"$host\"}",
     "legendFormat": "physmem"
    },
    {
     "expr": "mem.util.free{hostname == \"$host\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Per-CPU ms/s busy (User)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.user{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Per-CPU ms/s busy (Sys)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.sys{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Context switches per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kernel.all.pswitch{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "Runnable",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.runnable{hostname == \"$host\"}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.used{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.cached{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.free{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgfault{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "Hard fault rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgmajfault{hostname == \"$host\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network Throughput (in)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Throughput (out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (In)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (Out)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (In)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (Out)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "TCP Timeouts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.timeouts{hostname == \"$host\"}"
    }
   ]
  },
  {
   "title": "TCP Listen Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.listenoverflows{hostname == \"$host\"}",
     "legendFormat": "overflows"
    },
    {
     "expr": "network.tcp.listendrops{hostname == \"$host\"}",
     "legendFormat": "drops"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.retranssegs{hostname == \"$host\"}",
     "legendFormat": "retranssegs"
    },
    {
     "expr": "network.tcp.fastretrans{hostname == \"$host\"}",
     "legendFormat": "fastretrans"
    },
    {
     "expr": "network.tcp.slowstartretrans{hostname == \"$host\"}",
     "legendFormat": "slowstartretrans"
    },
    {
     "expr": "network.tcp.synretrans{hostname == \"$host\"}",
     "legendFormat": "synretrans"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_rawactive{hostname == \"$host\"}",
     "legendFormat": "$instance"
    },
    {
     "expr": "disk.dev.write_rawactive{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read{hostname == \"$host\"}",
     "legendFormat": "$instance"
    },
    {
     "expr": "disk.dev.write{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    },
    {
     "expr": "disk.dev.write_bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk.dev.avactive{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  }
 ]
}